#!/bin/bash
tarname="pa2_olds.tar"

rm $tarname
cp src/BigramCount.java .
javac BigramCount.java -Xlint:deprecation -d ./target/classes
cp target/classes/BigramCount*.class .
jar -cvf BigramCount.jar BigramCount*.class 
rm ./BigramCount*.class
#rm -R output
hadoop jar BigramCount.jar BigramCount input output
tar -cvf $tarname input output BigramCount.java answer.txt
cat ./output/part-r-00000