#!/bin/bash
cp src/BigramCount.java .
javac BigramCount.java -Xlint:deprecation
jar -cvf BigramCount.jar ./BigramCount*.class -d ./target/classes
rm ./BigramCount*.class
hadoop jar BigramCount.jar BigramCount input output
tar -cvf pa2_olds.tar input output BigramCount.java answer.txt
cat ./output/part-r-00000

